name: Auto Create PullRequest
on:
  pull_request:
    types: [opened, edited, ready_for_review, converted_to_draft]
    branches:
      - "master"

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'gh pr create --base master --head feature/add --title $TITLE'
          echo ${{ toJson(github.event.pull_request) }}
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.event.pull_request.body }}
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.repository }}
        env:
          TITLE: ${{ github.pull_request.title }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
