on: [push, pull_request]

jobs:
  docker_version:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://gcr.io/cloud-builders/gcloud
        with:
          args: version

  args_test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/echo
          args: Hello World!

  pwsls:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls
        working-directory: /tmp
