on: [push, pull_request]

env:
  SCOPE: workflows

jobs:
  # docker_version:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: docker://gcr.io/cloud-builders/gcloud
  #      with:
  #        args: version

  args_test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/echo
          args: Hello World!

  pwdls:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls
        working-directory: /tmp

  python:
    runs-on: ubuntu-latest
    steps:
      - run: |
          import sys
          print(sys.version)
        shell: python

  eux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
        shell: bash -eux {0}

  other:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - run: sleep 1
        timeout-minutes: 1

  echoenv:
    runs-on: ubuntu-latest
    env:
      SCOPE: jobs
    steps:
      - run: echo ${SCOPE}
      - env:
          SCOPE: steps
        run: echo ${SCOPE}
