name: Use GitHub Token
on: push

jobs:
  tokens:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          --request GET \
          --url https://api.github.com/repos/${{github.repository}}/issues \
          --header 'Authorization: Bearer ${{secrets.GITHUB_TOKEN}}'
