name: if
on: [push, pull_request]

env:
  SCOPE: workflows

jobs:
  empty:
    if: github.head_ref == ''
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"

  master:
    runs-on: ubuntu-latest
    steps:
      - if: startsWith(github.head_ref, 'master')
        run: echo "${{ github.head_ref }}"

  release:
    runs-on: ubuntu-latest
    steps:
      - if: startsWith(github.head_ref, 'release')
        run: echo "${{ github.head_ref }}"
