name: if
on: [push, pull_request]

env:
  SCOPE: workflows

jobs:
  empty:
    if: github.head_ref == ''
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"

  mas:
    if: github.head_ref == 'mas*'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"

  rel:
    if: github.head_ref == 'rel*'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"
