name: test
on: workflow_dispatch
jobs:
  js_action:
    runs-on: ubuntu-latest
    name: test js action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        id: getinput
        run: |
          testJson=`cat ./input.json | tr -d '\n'`
          echo "::set-output name=testdata::$testJson"

      - name: Create Message
        uses: ./.github/actions/helloworld
        id: create-message
        with:
          json-data: ${{ steps.getinput.outputs.testdata}}
      - name: Output Message
        run: echo ${{ steps.create-message.outputs.result-message }}
