name: Ready for Review
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  build:
    name: Echo Message
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ready for Review. ready from the beginning"
      - run: echo "Draft ${{ github.event.pull_request.draft }} "
