name: Ready for Review
on:
  pull_request:
    types: [ready_for_review]

jobs:
  build:
    name: Echo Message
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ready for Review. draft to ready"
